In [11]:
import pandas as pd
import numpy as np

In [12]:
cftr = pd.read_csv(r"D:\CFTR\final_cftr_dataset.csv")

gnom = pd.read_csv(r"D:\CFTR\gnomAD_v4.1.1_ENSG00000001626_2026_04_13_12_57_13.csv")
gnom.head()

,gnomAD ID,Chromosome,Position,rsIDs,Reference,Alternate,Source,Filters - exomes,Filters - genomes,Transcript,...,Homozygote Count Amish,Hemizygote Count Amish,Allele Count South Asian,Allele Number South Asian,Homozygote Count South Asian,Hemizygote Count South Asian,Allele Count Remaining,Allele Number Remaining,Homozygote Count Remaining,Hemizygote Count Remaining
0,7-117480021-CAG-C,7,117480021,NaN,CAG,C,gnomAD Exomes,PASS,NaN,ENST00000648260.1,...,0,0,1,86294,0,0,0,54566,0,0
1,7-117480025-G-A,7,117480025,NaN,G,A,gnomAD Exomes,PASS,NaN,ENST00000003084.11,...,0,0,3,86894,0,0,0,55456,0,0
2,7-117480026-T-C,7,117480026,NaN,T,C,gnomAD Exomes,PASS,NaN,ENST00000003084.11,...,0,0,1,86808,0,0,0,55372,0,0
3,7-117480028-G-A,7,117480028,NaN,G,A,gnomAD Exomes,PASS,NaN,ENST00000003084.11,...,0,0,1,87548,0,0,0,56518,0,0
4,7-117480029-T-C,7,117480029,rs1797974971,T,C,"gnomAD Exomes,gnomAD Genomes",PASS,PASS,ENST00000003084.11,...,0,0,0,87626,0,0,0,56670,0,0

In [13]:
gnom.columns

Index(['gnomAD ID', 'Chromosome', 'Position', 'rsIDs', 'Reference',
       'Alternate', 'Source', 'Filters - exomes', 'Filters - genomes',
       'Transcript', 'HGVS Consequence', 'Protein Consequence',
       'Transcript Consequence', 'VEP Annotation',
       'ClinVar Germline Classification', 'ClinVar Variation ID', 'Flags',
       'Allele Count', 'Allele Number', 'Allele Frequency', 'Homozygote Count',
       'Hemizygote Count', 'Filters - joint', 'GroupMax FAF group',
       'GroupMax FAF frequency', 'cadd', 'revel_max', 'spliceai_ds_max',
       'pangolin_largest_ds', 'phylop', 'sift_max', 'polyphen_max',
       'Allele Count African/African American',
       'Allele Number African/African American',
       'Homozygote Count African/African American',
       'Hemizygote Count African/African American',
       'Allele Count Admixed American', 'Allele Number Admixed American',
       'Homozygote Count Admixed American',
       'Hemizygote Count Admixed American', 'Allele Count Ashkenazi Jewish',
       'Allele Number Ashkenazi Jewish', 'Homozygote Count Ashkenazi Jewish',
       'Hemizygote Count Ashkenazi Jewish', 'Allele Count East Asian',
       'Allele Number East Asian', 'Homozygote Count East Asian',
       'Hemizygote Count East Asian', 'Allele Count European (Finnish)',
       'Allele Number European (Finnish)',
       'Homozygote Count European (Finnish)',
       'Hemizygote Count European (Finnish)', 'Allele Count Middle Eastern',
       'Allele Number Middle Eastern', 'Homozygote Count Middle Eastern',
       'Hemizygote Count Middle Eastern',
       'Allele Count European (non-Finnish)',
       'Allele Number European (non-Finnish)',
       'Homozygote Count European (non-Finnish)',
       'Hemizygote Count European (non-Finnish)', 'Allele Count Amish',
       'Allele Number Amish', 'Homozygote Count Amish',
       'Hemizygote Count Amish', 'Allele Count South Asian',
       'Allele Number South Asian', 'Homozygote Count South Asian',
       'Hemizygote Count South Asian', 'Allele Count Remaining',
       'Allele Number Remaining', 'Homozygote Count Remaining',
       'Hemizygote Count Remaining'],
      dtype='object')

In [14]:
gnom = gnom[gnom["Allele Frequency"] > 0.001]

In [15]:
gnom = gnom[[
    "Chromosome",
    "Position",
    "Reference",
    "Alternate",
    "Allele Frequency",
    "ClinVar Germline Classification"
]]

gnom.head()

,Chromosome,Position,Reference,Alternate,Allele Frequency,ClinVar Germline Classification
56,7,117480087,G,C,0.051868,Benign/Likely benign
253,7,117504290,C,T,0.001508,Conflicting classifications of pathogenicity
325,7,117504391,A,G,0.001308,Uncertain significance
374,7,117505178,G,C,0.001011,NaN
471,7,117509093,G,A,0.030080,Conflicting classifications of pathogenicity

In [16]:
gnom["Chromosome"].value_counts()

Chromosome
7    55
Name: count, dtype: int64

In [18]:
cftr.columns

Index(['Variant cDNA name', 'variant determination', 'hgvs_genomic_grch38',
       'chr', 'pos', 'ref', 'alt', 'cause', 'Name', 'Canonical SPDI',
       'dbSNP ID', 'Variant type', 'Germline classification'],
      dtype='object')

In [19]:
gnom["cause"] = 0

In [20]:
gnom.rename(columns={"Chromosome": "chr", "Position": "pos", "Reference": "ref", "Alternate": "alt"}, inplace = True)
gnom.columns

Index(['chr', 'pos', 'ref', 'alt', 'Allele Frequency',
       'ClinVar Germline Classification', 'cause'],
      dtype='object')

In [21]:
cftr["chr"] = cftr["chr"].astype(str)
gnom["chr"] = gnom["chr"].astype(str)

cftr["pos"] = cftr["pos"].astype(int)
gnom["pos"] = gnom["pos"].astype(int)

In [22]:
final_dataset = pd.concat([cftr, gnom], ignore_index=True)

final_dataset = final_dataset.drop_duplicates(
    subset=["chr", "pos", "ref", "alt"],
    keep="first"   
)

In [23]:
final_dataset = final_dataset.sample(frac=1, random_state=123).reset_index(drop=True)

In [24]:
final_dataset.head()

,Variant cDNA name,variant determination,hgvs_genomic_grch38,chr,pos,ref,alt,cause,Name,Canonical SPDI,dbSNP ID,Variant type,Germline classification,Allele Frequency,ClinVar Germline Classification
0,NaN,NaN,NaN,chr7,117603746,C,T,1,NM_000492.4(CFTR):c.2872C>T (p.Gln958Ter),NC_000007.14:117603745:C:T,rs2116062284,single nucleotide variant,Pathogenic,NaN,NaN
1,c.3539_3554del,CF-causing,NC_000007.14:g.117627592_117627607del,chr7,117627591,AAACCATACAAGAATGG,A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c.3140-26A>G,CF-causing,NC_000007.14:g.117611555A>G,chr7,117611555,A,G,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,c.1486T>G,CF-causing,NC_000007.14:g.117559557T>G,chr7,117559557,T,G,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,c.937_938del,CF-causing,NC_000007.14:g.117540167_117540168del,chr7,117540164,TTC,T,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
final_dataset.to_csv(r"D:\CFTR\final_cftr_dataset.csv", index=False)
print("Done")

Done